"use client";
import React, { useState } from "react";
import { usePopup } from "./PopupContext";
import CrawlSimulation from "./CrawlSimulation";
import { 
  ArrowUpRight, Star, ArrowRight, Check,
  Clock, Zap, Sparkles, Plus, Cpu, Globe
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const easeWeb: [number, number, number, number] = [0.16, 1, 0.3, 1];
const fadeInUp = {
  initial: { opacity: 0, y: 35 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-120px" },
  transition: { duration: 0.8, ease: easeWeb }
};

const StaticHomepage: React.FC = () => {
  const { openPopup } = usePopup();

  // State controls
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [isYearly, setIsYearly] = useState(false);

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const steps = [
    {
      num: "Step 01",
      title: "Add Projects & Sitemaps",
      desc: "Create projects in seconds. Add your website or sitemap and organize audits by client or campaign."
    },
    {
      num: "Step 02",
      title: "Run Deep SEO Audits",
      desc: "Crawl up to 10,000 URLs per project. Identify technical SEO issues, broken links, missing tags, and performance gaps instantly."
    },
    {
      num: "Step 03",
      title: "Analyze, Fix & Improve",
      desc: "Get structured audit reports with scores, issue breakdowns, and (soon) AI-powered recommendations to fix problems faster."
    }
  ];

  const faqs = [
    {
      q: "Can I use the license on multiple devices?",
      a: "Yes, depending on your plan. The Pro plan allows activation on up to 2 personal devices, and the Advanced plan allows up to 5 devices across your team."
    },
    {
      q: "What is included in the Free plan?",
      a: "The Free plan includes up to 5 active projects, basic crawl capabilities for up to 1,000 URLs per project, and core technical SEO checks including meta tags, broken link detection, and image analysis."
    },
    {
      q: "What happens when I reach my URL limit?",
      a: "Once the crawl hits your plan's URL limit, it will pause. You will still be able to explore all data and export reports for the crawled portion. To scan more URLs, you can upgrade your plan at any time."
    },
    {
      q: "Does the app work offline?",
      a: "CrawlBeast runs locally on your desktop, meaning database lookups and report navigation work completely offline. However, to crawl active live websites, an active internet connection is required."
    },
    {
      q: "How do I receive my license after payment?",
      a: "Your activation license key is generated immediately after purchase and sent to your email address, along with instructions to download and activate the desktop application."
    }
  ];

  const testimonials = [
    {
      initials: "SM",
      name: "Sophia Miller",
      role: "VP of SEO · Scale Agency",
      text: "“CrawlBeast reduced our technical audit workflow by 70%. The white-label reporting is clean, clear, and presentation-ready. Our clients read them, and the task prioritization makes execution effortless.”"
    },
    {
      initials: "LB",
      name: "Lucas Bennett",
      role: "Technical SEO Consultant",
      text: "“I have tested every crawler out there. CrawlBeast’s memory-efficient desktop crawling is incredible. It captured complex JavaScript rendering errors that other tools glossed over entirely. Highly recommended.”"
    },
    {
      initials: "CD",
      name: "Chloe Davies",
      role: "Head of E-commerce · ShopVibe (Shopify Plus)",
      text: "“Our store audit revealed 340 duplicate meta descriptions generated by our layout theme. We fixed them within a week and recorded a 23% organic session boost inside two months. Excellent software.”"
    },
    {
      initials: "EK",
      name: "Ethan Kim",
      role: "Director of SEO · Global Scale Corp",
      text: "“We crawled 85,000 pages across a dozen international domains. CrawlBeast processed it all natively without breaking a sweat. The automated data exporter saved our engineering department weeks of custom scripting.”"
    },
    {
      initials: "OW",
      name: "Olivia Wright",
      role: "Local SEO Director · Dental Group",
      text: "“Handling local NAP audits for 28 clinics was a tedious task. CrawlBeast’s dashboard gives us a unified view of citation consistency, GMB details, and local directory listings across all branches.”"
    },
    {
      initials: "NT",
      name: "Noah Taylor",
      role: "B2B Search Strategist · SaaS Enterprise",
      text: "“The B2B crawling capabilities are top-notch. It easily highlights indexability bottlenecks on complex SaaS platforms. The exportable reports make pitching prospective clients much more convincing.”"
    }
  ];

  const plans = [
    {
      name: "Free Plan",
      desc: "Perfect for beginners and small audits.",
      priceMonthly: 0,
      priceYearly: 0,
      features: [
        "Crawl up to 1,000 URLs",
        "Up to 5 active projects",
        "Core SEO checks (meta, links, images)",
        "Community support forums",
        "All future features included",
        "Email Support"
      ],
      cta: "Download Now",
      featured: false
    },
    {
      name: "Pro Plan",
      desc: "For freelancers and SEO professionals.",
      priceMonthly: 12,
      priceYearly: 9,
      features: [
        "Crawl up to 20,000 URLs",
        "Up to 100 active projects",
        "All SEO checks enabled",
        "Faster crawling performance",
        "All future features included",
        "Email Support"
      ],
      cta: "Start Now",
      featured: true
    },
    {
      name: "Advanced Plan",
      desc: "For agencies and heavy search users.",
      priceMonthly: 22,
      priceYearly: 19,
      features: [
        "Crawl up to 100,000 URLs",
        "Unlimited active projects",
        "Priority crawl speed settings",
        "Detailed csv exporter scripts",
        "All future features included",
        "Email Support"
      ],
      cta: "Start Now",
      featured: false
    }
  ];

  return (
    <div className="flex-1">
      {/* Hero Section */}
      <motion.section {...fadeInUp} className="relative pt-24 pb-16 md:pt-32 md:pb-24 overflow-hidden bg-grid-pattern">
        <div className="max-w-7xl mx-auto px-6 text-center flex flex-col items-center">
          {/* Badge */}
          <div className="inline-flex flex-wrap items-center justify-center gap-3 mb-6">
            <span className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-xs font-semibold bg-primary/10 border border-primary/20 text-secondary">
              <Sparkles className="h-3.5 w-3.5" />
              Unlock Smarter SEO
            </span>
            <span className="text-xs font-medium text-zinc-400 flex items-center gap-1">
              <span className="text-[#fbbf24] flex items-center gap-0.5">
                <Star className="h-3.5 w-3.5 fill-[#fbbf24]" />
                <Star className="h-3.5 w-3.5 fill-[#fbbf24]" />
                <Star className="h-3.5 w-3.5 fill-[#fbbf24]" />
                <Star className="h-3.5 w-3.5 fill-[#fbbf24]" />
                <Star className="h-3.5 w-3.5 fill-[#fbbf24]" />
              </span>
              4.9 from 100+ reviews
            </span>
          </div>

          <h1 className="text-4xl md:text-7xl font-extrabold tracking-tight mb-6 max-w-4xl leading-tight md:leading-none">
            Turn SEO Insights <br />
            <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
              Into Revenue.
            </span>
          </h1>

          <p className="text-zinc-400 text-base md:text-xl max-w-2xl leading-relaxed mb-8">
            Run powerful SEO audits directly from your desktop. Analyze websites, uncover critical issues, and turn data into actionable insights faster than ever.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 mb-3 w-full sm:w-auto">
            <button
              onClick={openPopup}
              className="w-full sm:w-auto bg-gradient-to-r from-primary to-secondary text-white font-semibold py-3.5 px-8 rounded-xl text-sm cursor-pointer shadow-lg shadow-primary/20 hover:brightness-110 transition-all active:scale-95"
            >
              Start Your Free Audit
            </button>
            <button
              onClick={openPopup}
              className="w-full sm:w-auto bg-white/5 border border-white/10 hover:border-zinc-700 text-white font-semibold py-3.5 px-8 rounded-xl text-sm cursor-pointer transition-colors"
            >
              Watch Demo
            </button>
          </div>
          <p className="text-[11px] text-zinc-600 font-medium uppercase tracking-wider">
            Download CrawlBeast and crawl up to 1,000 URLs for free.
          </p>

          {/* Interactive Widget Overlay */}
          <div className="w-full mt-16 md:mt-24">
            <CrawlSimulation />
          </div>
        </div>
      </motion.section>

      {/* Our Approach Section */}
      <motion.section {...fadeInUp} className="py-24 border-t border-white/5 bg-[#080b11]/50" id="about">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <span className="inline-flex px-3.5 py-1.5 rounded-full text-xs font-semibold bg-primary/10 border border-primary/20 text-secondary mb-3 uppercase tracking-wider">
              Our Approach
            </span>
            <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight mb-4">
              Simple Steps to Get Started
            </h2>
            <p className="text-zinc-400 text-base leading-relaxed">
              Your all-in-one SEO audit workflow, built for speed, clarity, and real results.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {steps.map((step, idx) => (
              <div 
                key={step.num}
                className="group relative bg-[#0e1320] border border-white/5 hover:border-primary/20 p-8 rounded-2xl transition-all duration-300 overflow-hidden"
              >
                <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-primary to-secondary opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <span className="inline-block font-mono text-xs text-primary font-bold py-1 px-2.5 bg-primary/10 border border-primary/20 rounded-md mb-6 uppercase tracking-wider">
                  {step.num}
                </span>
                <h3 className="text-lg font-bold text-white mb-3">{step.title}</h3>
                <p className="text-zinc-400 text-sm leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>

          <div className="text-center mt-12">
            <button
              onClick={openPopup}
              className="bg-gradient-to-r from-primary to-secondary text-white font-semibold py-3 px-8 rounded-xl text-sm cursor-pointer shadow-lg shadow-primary/15 transition-transform active:scale-95"
            >
              Download Now
            </button>
          </div>
        </div>
      </motion.section>

      {/* Bento Grid Features Section */}
      <motion.section {...fadeInUp} className="py-24 border-t border-white/5" id="features">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <span className="inline-flex px-3.5 py-1.5 rounded-full text-xs font-semibold bg-primary/10 border border-primary/20 text-secondary mb-3 uppercase tracking-wider">
              Solve Real Problems
            </span>
            <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight mb-4">
              Everything You Need to Audit & Scale SEO
            </h2>
            <p className="text-zinc-400 text-base leading-relaxed">
              Built specifically for freelancers, consultants, and agencies who need fast, reliable SEO insights.
            </p>
          </div>

          {/* Bento Grid Layout */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Box 1: Structured Audit Reports */}
            <div className="md:col-span-2 bg-[#0e1320] border border-white/5 hover:border-primary/20 p-8 rounded-2xl flex flex-col justify-between transition-all duration-300">
              <div>
                <div className="h-10 w-10 bg-primary/10 border border-primary/20 text-secondary rounded-lg flex items-center justify-center mb-6">
                  <Zap className="h-5 w-5" />
                </div>
                <h3 className="text-xl font-bold text-white mb-2">Structured Audit Reports</h3>
                <p className="text-zinc-400 text-sm leading-relaxed max-w-xl mb-6">
                  Get clear, structured insights to streamline your auditing workflows. Drill down into individual resource segments immediately:
                </p>
              </div>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm font-semibold text-zinc-300">
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-success block" /> Total URLs crawled
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-success block" /> Success vs failed pages
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-success block" /> SEO health scores
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-success block" /> Issue breakdowns
                </li>
              </ul>
            </div>

            {/* Box 2: Desktop Performance */}
            <div className="bg-[#0e1320] border border-white/5 hover:border-primary/20 p-8 rounded-2xl flex flex-col justify-between transition-all duration-300">
              <div>
                <div className="h-10 w-10 bg-primary/10 border border-primary/20 text-secondary rounded-lg flex items-center justify-center mb-6">
                  <Cpu className="h-5 w-5" />
                </div>
                <h3 className="text-xl font-bold text-white mb-2">Desktop Performance</h3>
                <p className="text-zinc-400 text-sm leading-relaxed mb-6">
                  No browser lag. No cloud delays. Run audit crawls locally directly on your desktop with speed and complete control.
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <span className="font-mono text-[10px] text-zinc-400 bg-white/5 border border-white/5 py-1 px-2.5 rounded">
                  Zero Lag
                </span>
                <span className="font-mono text-[10px] text-zinc-400 bg-white/5 border border-white/5 py-1 px-2.5 rounded">
                  Local Database
                </span>
              </div>
            </div>

            {/* Box 3: Powerful Website Crawling */}
            <div className="bg-[#0e1320] border border-white/5 hover:border-primary/20 p-8 rounded-2xl flex flex-col justify-between transition-all duration-300">
              <div>
                <div className="h-10 w-10 bg-primary/10 border border-primary/20 text-secondary rounded-lg flex items-center justify-center mb-6">
                  <Globe className="h-5 w-5" />
                </div>
                <h3 className="text-xl font-bold text-white mb-2">Powerful Website Crawling</h3>
                <p className="text-zinc-400 text-sm leading-relaxed mb-6">
                  Scan entire websites and sitemaps with absolute precision. Identify critical technical errors, broken internal paths, and accessibility discrepancies across all pages without relying on cloud limitations.
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <span className="font-mono text-[10px] text-zinc-400 bg-white/5 border border-white/5 py-1 px-2.5 rounded">
                  No Proxy Required
                </span>
                <span className="font-mono text-[10px] text-zinc-400 bg-white/5 border border-white/5 py-1 px-2.5 rounded">
                  Multi-threaded Engine
                </span>
              </div>
            </div>

            {/* Box 4: AI Insights */}
            <div className="md:col-span-2 relative bg-gradient-to-br from-primary/5 via-[#0e1320] to-[#0e1320] border border-white/5 hover:border-primary/20 p-8 rounded-2xl flex flex-col justify-between transition-all duration-300 overflow-hidden">
              <span className="absolute top-6 right-6 font-mono text-[10px] font-bold text-warning bg-warning/10 border border-warning/20 py-1 px-3 rounded-full uppercase tracking-wider">
                Coming Soon
              </span>
              <div>
                <div className="h-10 w-10 bg-secondary/10 border border-secondary/20 text-secondary rounded-lg flex items-center justify-center mb-6">
                  <Sparkles className="h-5 w-5" />
                </div>
                <h3 className="text-xl font-bold bg-gradient-to-r from-white to-secondary bg-clip-text text-transparent mb-2">
                  AI-Powered SEO Insights
                </h3>
                <p className="text-zinc-400 text-sm leading-relaxed max-w-xl mb-6">
                  Turn raw audit data into high-value actionable strategies. Automatically generate detailed explanations, impact scores, and technical fixes.
                </p>
              </div>
              <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm font-semibold text-zinc-400">
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-primary block" /> Detailed issue explanations
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-primary block" /> Actionable fix recommendations
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-primary block" /> Priority scoring based on impact
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-primary block" /> Content & technical suggestions
                </li>
              </ul>
            </div>
          </div>

          <div className="text-center mt-12">
            <button
              onClick={openPopup}
              className="bg-gradient-to-r from-primary to-secondary text-white font-semibold py-3 px-8 rounded-xl text-sm cursor-pointer shadow-lg shadow-primary/15 transition-transform active:scale-95"
            >
              Get Started Today
            </button>
          </div>
        </div>
      </motion.section>

      {/* Clients Success (The CrawlBeast Effect) */}
      <motion.section {...fadeInUp} className="py-24 border-t border-white/5 bg-[#080b11]/50" id="success">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <span className="inline-flex px-3.5 py-1.5 rounded-full text-xs font-semibold bg-primary/10 border border-primary/20 text-secondary mb-3 uppercase tracking-wider">
              Clients Success
            </span>
            <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight mb-4">
              The CrawlBeast Effect
            </h2>
            <p className="text-zinc-400 text-base leading-relaxed">
              See how high-growth businesses and agencies transform their search presence and workflow speed.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Metric Card 1 */}
            <div className="bg-[#0e1320] border border-white/5 p-8 rounded-2xl flex flex-col justify-between hover:border-zinc-800 transition-colors">
              <div>
                <div className="flex justify-between items-center text-xs font-bold text-zinc-500 uppercase tracking-widest mb-6">
                  <span>Audit Time Diagnostics</span>
                  <Clock className="h-4 w-4 text-zinc-600" />
                </div>
                
                {/* Visual Speed comparison */}
                <div className="space-y-4 mb-6">
                  <div>
                    <div className="flex justify-between text-xs text-zinc-400 mb-1 font-semibold">
                      <span>Standard Cloud Audit</span>
                      <span>12 Hours</span>
                    </div>
                    <div className="h-2 w-full bg-white/5 rounded-full overflow-hidden">
                      <div className="h-full bg-zinc-600 rounded-full w-full" />
                    </div>
                  </div>
                  <div>
                    <div className="flex justify-between text-xs text-primary mb-1 font-semibold">
                      <span>CrawlBeast Desktop Audit</span>
                      <span>15 Minutes</span>
                    </div>
                    <div className="h-2 w-full bg-white/5 rounded-full overflow-hidden">
                      <div className="h-full bg-gradient-to-r from-primary to-secondary rounded-full w-[2.1%] shadow-[0_0_8px_rgba(6,118,254,0.8)]" />
                    </div>
                  </div>
                </div>

                <div className="text-4xl font-extrabold font-mono text-rose-500 tracking-tight leading-none mb-1">
                  -97.9%
                </div>
                <div className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider mb-6">
                  Time Saved Optimization Rate
                </div>

                <p className="text-zinc-400 text-sm italic leading-relaxed border-l border-primary pl-4 mb-6">
                  “Technical SEO audit times dropped from 12 hours to 15 minutes, allowing us to pitch 4x more clients.”
                </p>
              </div>
              
              <div className="flex items-center gap-3 pt-4 border-t border-white/5">
                <div className="h-9 w-9 bg-primary/10 border border-primary/20 text-secondary text-xs font-bold rounded-full flex items-center justify-center">
                  OG
                </div>
                <div>
                  <h6 className="text-xs font-bold text-white">Olaf van Gastel</h6>
                  <p className="text-[10px] text-zinc-500 font-medium">Founder · Bright Brands</p>
                </div>
              </div>
            </div>

            {/* Metric Card 2 */}
            <div className="bg-[#0e1320] border border-white/5 p-8 rounded-2xl flex flex-col justify-between hover:border-zinc-800 transition-colors">
              <div>
                <div className="flex justify-between items-center text-xs font-bold text-zinc-500 uppercase tracking-widest mb-6">
                  <span>Search Performance</span>
                  <Star className="h-4 w-4 text-zinc-600" />
                </div>

                <div className="text-4xl font-extrabold font-mono text-secondary tracking-tight leading-none mb-1">
                  96%
                </div>
                <div className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider mb-4 flex items-center gap-1.5">
                  <span className="text-success">▲</span> +54% improvement SEO Health Score
                </div>

                <div className="text-2xl font-extrabold font-mono text-white tracking-tight leading-none mb-1">
                  +210%
                </div>
                <div className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider mb-6">
                  Organic Visibility Impressions
                </div>

                <p className="text-zinc-400 text-sm italic leading-relaxed border-l border-primary pl-4 mb-6">
                  “Our SEO health score went from 42% to 96% in 2 weeks, and search impressions tripled shortly after.”
                </p>
              </div>
              
              <div className="flex items-center gap-3 pt-4 border-t border-white/5">
                <div className="h-9 w-9 bg-primary/10 border border-primary/20 text-secondary text-xs font-bold rounded-full flex items-center justify-center">
                  LN
                </div>
                <div>
                  <h6 className="text-xs font-bold text-white">Lorenzo Nicolini</h6>
                  <p className="text-[10px] text-zinc-500 font-medium">Founder · Moonb</p>
                </div>
              </div>
            </div>

            {/* Metric Card 3 */}
            <div className="bg-[#0e1320] border border-white/5 p-8 rounded-2xl flex flex-col justify-between hover:border-zinc-800 transition-colors">
              <div>
                <div className="flex justify-between items-center text-xs font-bold text-zinc-500 uppercase tracking-widest mb-6">
                  <span>AI Bot Indexing</span>
                  <Sparkles className="h-4 w-4 text-zinc-600" />
                </div>

                <div className="text-4xl font-extrabold font-mono text-white tracking-tight leading-none mb-1">
                  48 Hrs
                </div>
                <div className="text-[10px] font-bold text-zinc-400 uppercase tracking-wider mb-4">
                  Crawl Indexing Latency (Was 14 Days)
                </div>

                <div className="flex flex-wrap gap-1.5 mb-6">
                  <span className="text-[9px] font-semibold bg-success/10 text-success border border-success/20 py-0.5 px-2 rounded-full">
                    Zero JS rendering blocks
                  </span>
                  <span className="text-[9px] font-semibold bg-primary/10 text-secondary border border-primary/20 py-0.5 px-2 rounded-full">
                    Ready for LLMs
                  </span>
                </div>

                <p className="text-zinc-400 text-sm italic leading-relaxed border-l border-primary pl-4 mb-6">
                  “The biggest shift: our pages got indexed by Gemini and ChatGPT within 48 hours of resolving rendering errors.”
                </p>
              </div>
              
              <div className="flex items-center gap-3 pt-4 border-t border-white/5">
                <div className="h-9 w-9 bg-primary/10 border border-primary/20 text-secondary text-xs font-bold rounded-full flex items-center justify-center">
                  AC
                </div>
                <div>
                  <h6 className="text-xs font-bold text-white">Aidan Cramer</h6>
                  <p className="text-[10px] text-zinc-500 font-medium">Co-founder · aiapply.co</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </motion.section>

      {/* Benefits Section & AI Ticker marquee */}
      <motion.section {...fadeInUp} className="py-24 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <span className="inline-flex px-3.5 py-1.5 rounded-full text-xs font-semibold bg-primary/10 border border-primary/20 text-secondary mb-3 uppercase tracking-wider">
              Benefits
            </span>
            <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight mb-4">
              Why SEO Professionals Choose This Tool
            </h2>
            <p className="text-zinc-400 text-base leading-relaxed">
              Our all-in-one platform simplifies your workflow so you can focus on what really matters growing your business.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
            <div className="bg-[#0e1320] border border-white/5 p-6 rounded-xl">
              <h4 className="font-bold text-white mb-2">Save Time & Effort</h4>
              <p className="text-zinc-400 text-xs leading-relaxed">
                Run complete website audits in minutes instead of hours.
              </p>
            </div>
            <div className="bg-[#0e1320] border border-white/5 p-6 rounded-xl">
              <h4 className="font-bold text-white mb-2">Deliver Better Results</h4>
              <p className="text-zinc-400 text-xs leading-relaxed">
                Spot deeper SEO issues others miss and improve rankings faster.
              </p>
            </div>
            <div className="bg-[#0e1320] border border-white/5 p-6 rounded-xl">
              <h4 className="font-bold text-white mb-2">Smarter Decisions</h4>
              <p className="text-zinc-400 text-xs leading-relaxed">
                Make high-impact SEO decisions backed by structured audit insights.
              </p>
            </div>
            <div className="bg-[#0e1320] border border-white/5 p-6 rounded-xl">
              <h4 className="font-bold text-white mb-2">Built for Real Workflows</h4>
              <p className="text-zinc-400 text-xs leading-relaxed">
                Designed for freelancers and agencies handling multiple clients.
              </p>
            </div>
          </div>

          {/* AI Search Optimization Marquee box */}
          <div className="bg-[#0e1320] border border-white/5 p-8 rounded-2xl flex flex-col lg:flex-row items-center justify-between gap-8 overflow-hidden">
            <div className="max-w-md">
              <h3 className="text-xl font-bold text-white mb-2">AI Search Optimization</h3>
              <p className="text-zinc-400 text-xs leading-relaxed">
                Ensure your website architecture, schema markings, and JavaScript rendering are optimized for AI search bot retrieval.
              </p>
            </div>
            
            {/* Ticker Container */}
            <div className="w-full lg:max-w-md overflow-hidden relative py-2">
              <div className="flex gap-4 animate-scroll-marquee whitespace-nowrap">
                <span className="inline-flex items-center gap-2 bg-white/5 border border-white/5 py-2 px-4 rounded-lg text-sm text-white font-medium">
                  <span className="h-1.5 w-1.5 rounded-full bg-secondary block" />
                  Claude
                </span>
                <span className="inline-flex items-center gap-2 bg-white/5 border border-white/5 py-2 px-4 rounded-lg text-sm text-white font-medium">
                  <span className="h-1.5 w-1.5 rounded-full bg-secondary block" />
                  Perplexity
                </span>
                <span className="inline-flex items-center gap-2 bg-white/5 border border-white/5 py-2 px-4 rounded-lg text-sm text-white font-medium">
                  <span className="h-1.5 w-1.5 rounded-full bg-secondary block" />
                  AI Overviews
                </span>
                <span className="inline-flex items-center gap-2 bg-white/5 border border-white/5 py-2 px-4 rounded-lg text-sm text-white font-medium">
                  <span className="h-1.5 w-1.5 rounded-full bg-secondary block" />
                  Gemini
                </span>
                <span className="inline-flex items-center gap-2 bg-white/5 border border-white/5 py-2 px-4 rounded-lg text-sm text-white font-medium">
                  <span className="h-1.5 w-1.5 rounded-full bg-secondary block" />
                  ChatGPT
                </span>
                <span className="inline-flex items-center gap-2 bg-white/5 border border-white/5 py-2 px-4 rounded-lg text-sm text-white font-medium">
                  <span className="h-1.5 w-1.5 rounded-full bg-secondary block" />
                  Grok
                </span>
              </div>
            </div>
          </div>
        </div>
      </motion.section>

      {/* Testimonials Section */}
      <motion.section {...fadeInUp} className="py-24 border-t border-white/5 bg-[#080b11]/50" id="testimonials">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <span className="inline-flex px-3.5 py-1.5 rounded-full text-xs font-semibold bg-primary/10 border border-primary/20 text-secondary mb-3 uppercase tracking-wider">
              Testimonials
            </span>
            <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight mb-4">
              Trusted by 1,200+ SEO Professionals
            </h2>
            <p className="text-zinc-400 text-base leading-relaxed">
              From freelance consultants to enterprise teams: what they say about CrawlBeast.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {testimonials.map((t) => (
              <div 
                key={t.name}
                className="bg-[#0e1320] border border-white/5 hover:border-zinc-800 p-6 rounded-xl flex flex-col justify-between transition-all duration-300 hover:-translate-y-1"
              >
                <p className="text-zinc-400 text-xs leading-relaxed mb-6 italic">{t.text}</p>
                <div className="flex items-center gap-3 pt-4 border-t border-white/5">
                  <div className="h-8 w-8 bg-primary/10 border border-primary/20 text-secondary text-xs font-bold rounded-full flex items-center justify-center">
                    {t.initials}
                  </div>
                  <div>
                    <h6 className="text-xs font-bold text-white">{t.name}</h6>
                    <p className="text-[10px] text-zinc-500 font-medium">{t.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </motion.section>

      {/* Embedded Pricing Section */}
      <motion.section {...fadeInUp} className="py-24 border-t border-white/5" id="pricing-homepage">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <span className="inline-flex px-3.5 py-1.5 rounded-full text-xs font-semibold bg-primary/10 border border-primary/20 text-secondary mb-3 uppercase tracking-wider">
              Pricing Plans
            </span>
            <h2 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight mb-4">
              Flexible Plans for Every Team Size
            </h2>
            <p className="text-zinc-400 text-sm md:text-base leading-relaxed">
              Simple, transparent pricing. Start free, upgrade when you need more power.
            </p>
          </div>

          {/* Toggle billing option */}
          <div className="flex items-center justify-center gap-4 mb-16">
            <button
              onClick={() => setIsYearly(false)}
              className={`text-sm font-semibold cursor-pointer transition-colors ${
                !isYearly ? "text-white" : "text-zinc-500 hover:text-zinc-300"
              }`}
            >
              Billed Monthly
            </button>
            
            <button
              onClick={() => setIsYearly(!isYearly)}
              className="w-12 h-7 rounded-full bg-white/10 border border-white/5 relative p-0.5 transition-colors cursor-pointer"
              aria-label="Toggle annual pricing"
            >
              <motion.div
                layout
                transition={{ type: "spring", stiffness: 500, damping: 30 }}
                className="w-5 h-5 rounded-full bg-gradient-to-r from-primary to-secondary"
                style={{ float: isYearly ? "right" : "left" }}
              />
            </button>

            <button
              onClick={() => setIsYearly(true)}
              className={`text-sm font-semibold cursor-pointer transition-colors flex items-center gap-2 ${
                isYearly ? "text-white" : "text-zinc-500 hover:text-zinc-300"
              }`}
            >
              Billed Annually
              <span className="text-[10px] font-bold text-success bg-success/10 border border-success/20 px-2 py-0.5 rounded-full uppercase tracking-wider">
                Save 20%
              </span>
            </button>
          </div>

          {/* Pricing Cards Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 max-w-5xl mx-auto items-stretch">
            {plans.map((plan) => {
              const currentPrice = isYearly ? plan.priceYearly : plan.priceMonthly;
              return (
                <div
                  key={plan.name}
                  className={`relative bg-[#0e1320] border rounded-2xl p-8 flex flex-col justify-between transition-all duration-300 ${
                    plan.featured
                      ? "border-primary shadow-2xl shadow-primary/5 lg:scale-105"
                      : "border-white/5 hover:border-zinc-800"
                  }`}
                >
                  {plan.featured && (
                    <span className="absolute -top-3 right-6 inline-flex items-center gap-1 bg-gradient-to-r from-primary to-secondary text-white font-bold text-[9px] uppercase tracking-wider py-1 px-3 rounded-full">
                      <Sparkles className="h-3 w-3" />
                      Most Popular
                    </span>
                  )}

                  <div>
                    <h3 className="text-xl font-bold text-white mb-2">{plan.name}</h3>
                    <p className="text-zinc-400 text-xs leading-relaxed mb-6">{plan.desc}</p>
                    
                    <div className="flex items-baseline gap-1.5 mb-8">
                      <span className="text-4xl md:text-5xl font-extrabold text-white font-mono tracking-tight">
                        ${currentPrice}
                      </span>
                      <span className="text-xs text-zinc-500 font-medium">
                        / month {isYearly && currentPrice > 0 ? ", billed annually" : ""}
                      </span>
                    </div>

                    <ul className="space-y-3.5 mb-8">
                      {plan.features.map((feature, fIdx) => (
                        <li key={fIdx} className="flex items-center gap-3 text-xs md:text-sm text-zinc-300 font-medium">
                          <Check className="h-4 w-4 text-secondary flex-shrink-0" />
                          <span>{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <button
                    onClick={openPopup}
                    className={`w-full py-3.5 px-6 rounded-xl text-sm font-semibold transition-all cursor-pointer active:scale-95 ${
                      plan.featured
                        ? "bg-gradient-to-r from-primary to-secondary text-white shadow-lg shadow-primary/10"
                        : "bg-white/5 border border-white/5 hover:border-zinc-700 text-white"
                    }`}
                  >
                    {plan.cta}
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      </motion.section>

      {/* FAQ Accordions */}
      <motion.section {...fadeInUp} className="py-24 border-t border-white/5 bg-[#080b11]/50">
        <div className="max-w-3xl mx-auto px-6">
          <div className="text-center mb-16">
            <span className="inline-flex px-3.5 py-1.5 rounded-full text-xs font-semibold bg-primary/10 border border-primary/20 text-secondary mb-3 uppercase tracking-wider">
              FAQs
            </span>
            <h2 className="text-3xl font-extrabold text-white tracking-tight mb-4">
              Everything You Need to Know
            </h2>
            <p className="text-zinc-400 text-sm leading-relaxed">
              Our platform brings everything you need into one place, making your work easier so you can concentrate on growing your business.
            </p>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div key={idx} className="bg-[#0e1320] border border-white/5 rounded-xl overflow-hidden transition-all duration-300">
                  <button
                    onClick={() => toggleFaq(idx)}
                    className="w-full flex justify-between items-center p-6 text-left font-semibold text-white text-sm md:text-base outline-none cursor-pointer"
                  >
                    {faq.q}
                    <span className={`transition-transform duration-300 ${isOpen ? "rotate-45 text-secondary" : ""}`}>
                      <Plus className="h-4.5 w-4.5 text-zinc-400" />
                    </span>
                  </button>
                  <AnimatePresence initial={false}>
                    {isOpen && (
                      <motion.div
                        initial={{ height: 0 }}
                        animate={{ height: "auto" }}
                        exit={{ height: 0 }}
                        transition={{ duration: 0.3, ease: "easeInOut" }}
                      >
                        <div className="p-6 pt-0 border-t border-white/3 text-zinc-400 text-xs md:text-sm leading-relaxed">
                          {faq.a}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </div>
        </div>
      </motion.section>

      {/* Final Welcome Banner */}
      <motion.section {...fadeInUp} className="py-24 border-t border-white/5 bg-gradient-to-b from-transparent to-[#05070a]">
        <div className="max-w-5xl mx-auto px-6">
          <div className="bg-gradient-to-br from-primary/10 via-[#0e1320] to-[#0e1320] border border-white/5 rounded-2xl p-12 md:p-16 text-center flex flex-col items-center relative overflow-hidden shadow-2xl">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 radial-glow pointer-events-none" />
            <h2 className="text-3xl md:text-5xl font-extrabold text-white tracking-tight mb-4">
              Welcome to CrawlBeast
            </h2>
            <p className="text-zinc-400 text-base max-w-lg mb-8 leading-relaxed">
              Your website audit is ready to get smarter. Download CrawlBeast for free and start finding the SEO issues that actually impact rankings.
            </p>
            <div className="flex gap-4">
              <button
                onClick={openPopup}
                className="bg-gradient-to-r from-primary to-secondary text-white font-semibold py-3 px-8 rounded-xl text-sm cursor-pointer shadow-lg shadow-primary/25 hover:brightness-110 active:scale-95 transition-all"
              >
                Download Now
              </button>
              <button
                onClick={() => window.location.href = '/pricing'}
                className="bg-white/5 border border-white/10 hover:border-zinc-700 text-white font-semibold py-3 px-8 rounded-xl text-sm cursor-pointer transition-colors"
              >
                View Pricing
              </button>
            </div>
          </div>
        </div>
      </motion.section>
    </div>
  );
};

export default StaticHomepage;
